apiVersion: "v1"
kind: "List"
items:
  - apiVersion: "v1"
    kind: "Service"
    metadata:
      annotations: {}
      labels: {}
      name: "aams"
    spec:
      selector:
        app: "aams"
      type: LoadBalancer
      externalIPs:
        - 192.168.49.2
      ports:
        - name: http
          port: 80
          targetPort: 80
          protocol: TCP
  - apiVersion: "apps/v1"
    kind: "Deployment"
    metadata:
      labels:
        app: "aams"
        version: "1.0.0"
      name: "aams"
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: "aams"
          version: "1.0.0"
      template:
        metadata:
          labels:
            app: "aams"
            version: "1.0.0"
        spec:
          containers:
          - image: "aams_image:latest"
            imagePullPolicy: "Never"
            name: "aams"
            resources:
              limits:
                cpu: 500m
              requests:
                cpu: 200m
            ports:
              - protocol: TCP
                containerPort: 80